version: '3.8'
services:
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        ports:
        - '5432:5432'
        volumes:
        - db:/var/lib/postgresql/data
    api:
        container_name: api
        build:
            context: ./api
        image: api
        depends_on:
            - db
        ports:
            - 4040:4040
        environment:
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_NAME: postgres
        links:
            - db
    ui:
        container_name: ui
        build:
            context: ./ui
        image: ui
        depends_on:
            - api
        ports:
            - 3000:3000
        links:
          - api
volumes:
    db:
        driver: local
