version: '3.8'
services:
    db:
        image: postgres:14.1-alpine
        restart: always
        env_file:
            - ./db/.env.production
        ports:
        - '5432:5432'
        volumes:
        - db:/var/lib/postgresql/data
        - ./db/init-prod.sql:/docker-entrypoint-initdb.d/create_tables.sql
    api:
        container_name: api
        build:
            context: ./api
        image: api
        depends_on:
            - db
        env_file:
            - ./api/.env.production
        ports:
            - 4040:4040
        links:
            - db
    ui:
        container_name: ui
        build:
            context: ./ui
        image: ui
        env_file:
            - ./ui/.env.production
        ports:
            - 3000:3000
        links:
          - api
    db-dev:
        image: postgres:14.1-alpine
        restart: always
        env_file:
            - ./db/.env.development
        ports:
        - '5432:5432'
        volumes:
        - db:/var/lib/postgresql/data
        - ./db/init-dev.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
    db:
        driver: local
