version: '3.8'
services:
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        ports:
        - '5432:5432'
        volumes:
        - db:/var/lib/postgresql/data
    api:
        container_name: api
        build:
            context: ./api
        image: api
        depends_on:
            - db
        ports:
            - 4040:4040
        env_file:
            - ./api/.env.production
        links:
            - db
    ui:
        container_name: ui
        build:
            context: ./ui
        image: ui
        depends_on:
            - api
        ports:
            - 3000:3000
        env_file:
            - ./ui/.env.production
        links:
          - api
    db-dev:
        image: postgres:14.1-alpine
        restart: always
        env_file:
            - ./db/.env.development
        ports:
        - '5432:5432'
        volumes:
        - db:/var/lib/postgresql/data
volumes:
    db:
        driver: local
